#!/bin/bash
echo "=== POST-IMPORT COUNTS ==="
su - postgres -c "psql -d sales_bot -c \"SELECT 'contacts' as tbl, COUNT(*) FROM contacts UNION ALL SELECT 'companies', COUNT(*) FROM companies UNION ALL SELECT 'deals', COUNT(*) FROM deals;\""
echo "=== DEALS BY STATE ==="
su - postgres -c "psql -d sales_bot -c \"SELECT current_state, COUNT(*) FROM deals GROUP BY current_state ORDER BY COUNT(*) DESC;\""
echo "=== CADENCE STEPS ==="
su - postgres -c "psql -d sales_bot -c \"SELECT cadence_step, COUNT(*) FROM deals GROUP BY cadence_step ORDER BY cadence_step;\""
echo "=== CONTACTS WITH EMAILS ==="
su - postgres -c "psql -d sales_bot -c \"SELECT COUNT(*) FROM contacts WHERE email != '' AND email IS NOT NULL;\""
echo "=== DEALS STEP 0 WITH CONTACTS ==="
su - postgres -c "psql -d sales_bot -c \"SELECT COUNT(DISTINCT d.id) FROM deals d JOIN companies c ON d.company_id = c.id JOIN contacts co ON co.company_id = c.id WHERE d.cadence_step = 0 AND d.current_state = 'Researched' AND co.email != '';\""
