#!/bin/bash
echo "=== CONTACTS ==="
su - postgres -c "psql -d sales_bot -c 'SELECT COUNT(*) as total, COUNT(email) as with_email FROM contacts;'"
echo "=== DEALS BY STATE ==="
su - postgres -c "psql -d sales_bot -c 'SELECT current_state, COUNT(*) FROM deals GROUP BY current_state ORDER BY COUNT(*) DESC;'"
echo "=== INTERACTIONS ==="
su - postgres -c "psql -d sales_bot -c 'SELECT COUNT(*) as total, COUNT(CASE WHEN direction = '\''outbound'\'' THEN 1 END) as outbound, COUNT(CASE WHEN direction = '\''inbound'\'' THEN 1 END) as inbound, COUNT(CASE WHEN success THEN 1 END) as success FROM interactions;'"
echo "=== RECENT DEALS ==="
su - postgres -c "psql -d sales_bot -c 'SELECT d.id, c.name, c.domain, d.current_state, d.updated_at FROM deals d JOIN companies c ON d.company_id = c.id ORDER BY d.updated_at DESC LIMIT 5;'"
echo "=== CADENCE ==="
su - postgres -c "psql -d sales_bot -c 'SELECT cadence_step, COUNT(*) FROM deals GROUP BY cadence_step ORDER BY cadence_step;'"
