package communication_test

import (
	"context"
	"os"
	"testing"
	"time"
	"strings"

	"github.com/robertpelloni/marketing_agent/internal/communication"
	"github.com/robertpelloni/marketing_agent/internal/db"
	"github.com/robertpelloni/marketing_agent/internal/llm"
)

type mockSender struct {
	sent []communication.EmailMessage
}

func (m *mockSender) Send(ctx context.Context, msg communication.EmailMessage) error {
	m.sent = append(m.sent, msg)
	return nil
}

func TestCadenceIntegration(t *testing.T) {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		t.Skip("DATABASE_URL not set, skipping integration test")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	database, err := db.NewDB(dbURL)
	if err != nil {
		t.Skipf("Failed to connect to database: %v", err)
	}
	defer func() { _ = database.Close() }()

	mockLLM := &llm.MockLLMProvider{}
	responder := communication.NewRAGResponseGenerator(database, mockLLM)
	sender := &mockSender{}
	mgr := communication.NewManager(database, nil, responder, nil, nil, sender)
	cam := communication.NewCadenceAwareManager(mgr, nil)

	// Setup testing data
	company := &db.Company{
		Name:          "Cadence Corp",
		Domain:        "cadence.com",
		MarketCapTier: "Mid-Market",
	}
	if err := database.CreateCompany(ctx, company); err != nil {
		t.Fatalf("CreateCompany failed: %v", err)
	}

	deal := &db.Deal{
		CompanyID:    company.ID,
		CurrentState: db.StateResearched,
	}
	if err := database.CreateDeal(ctx, deal); err != nil {
		t.Fatalf("CreateDeal failed: %v", err)
	}

	contact := &db.Contact{
		CompanyID: company.ID,
		Name:      "Cadence Lead",
		Email:     "lead@cadence.com",
	}
	if err := database.CreateContact(ctx, contact); err != nil {
		t.Fatalf("CreateContact failed: %v", err)
	}

	// Trigger CheckCadence
	cam.ExecuteCadenceCheck(ctx)

	// Verify that something was sent or an interaction was generated
	interactions, err := database.ListInteractionsByContact(ctx, contact.ID)
	if err != nil {
		t.Fatalf("ListInteractionsByContact failed: %v", err)
	}

	if len(interactions) == 0 {
		t.Fatalf("Expected an interaction to be created")
	}

    foundOutbound := false
    for _, i := range interactions {
        if i.Direction == "Outbound" {
            foundOutbound = true
            // Check that the template did not use bracketed placeholders
            if strings.Contains(i.RawText, "[") || strings.Contains(i.RawText, "]") {
                t.Errorf("Found bracketed placeholder in drafted interaction: %s", i.RawText)
            }
        }
    }

    if !foundOutbound {
        t.Errorf("No outbound interactions generated by cadence check")
    }

	if len(sender.sent) > 0 {
		msg := sender.sent[0]
		if strings.Contains(msg.Body, "[") || strings.Contains(msg.Body, "]") {
			t.Errorf("Found bracketed placeholder in sent email: %s", msg.Body)
		}
	}
}
