package assimilation

import "sort"

// SourceToolchain describes an upstream system targeted for native assimilation.
type SourceToolchain struct {
	ID               string   `json:"id"`
	DisplayName      string   `json:"displayName"`
	Language         string   `json:"language"`
	Category         string   `json:"category"`
	UpstreamPath     string   `json:"upstreamPath"`
	Strengths        []string `json:"strengths"`
	Noteworthy       []string `json:"noteworthy"`
	AssimilationPlan []string `json:"assimilationPlan"`
}

func Inventory() []SourceToolchain {
	items := []SourceToolchain{
		{
			ID:               "tormentnexus",
			DisplayName:      "TormentNexus",
			Language:         "TypeScript + Go",
			Category:         "control-plane",
			UpstreamPath:     "../tormentnexus",
			Strengths:        []string{"MCP aggregation", "provider routing", "memory and session substrate", "operator observability"},
			Noteworthy:       []string{"Best existing fit for TormentNexus-native provider routing and MCP management.", "Should remain the substrate instead of being reimplemented in the new harness."},
			AssimilationPlan: []string{"Consume as the default local control plane.", "Expose TormentNexus routes and tool inventories as native Go adapters.", "Let the new harness own the agent UX and exact tool contracts while TormentNexus owns orchestration truth."},
		},
		{ID: "pi", DisplayName: "Pi", Language: "TypeScript", Category: "foundation", UpstreamPath: "pi-cli", Strengths: []string{"minimal harness", "excellent extension seams", "interactive/json/rpc modes", "tool-first design"}, Noteworthy: []string{"The cleanest conceptual base for a Go rewrite.", "Good default philosophy: small core, user-extensible edges."}, AssimilationPlan: []string{"Port agent runtime contracts first.", "Mirror session model, settings, command surface, and extension seams.", "Retain exact default tool names and event vocabulary."}},
		{ID: "aider", DisplayName: "Aider", Language: "Python", Category: "coding-agent", UpstreamPath: "aider", Strengths: []string{"repo map", "edit strategies", "git-aware workflow"}, Noteworthy: []string{"Best-in-class context condensation for large repos.", "Multiple edit coders are a proven pattern worth preserving."}, AssimilationPlan: []string{"Port repomap and edit strategies as pluggable Go context engines.", "Keep git-native UX and commit-oriented workflows."}},
		{ID: "adrenaline", DisplayName: "Adrenaline", Language: "TypeScript", Category: "coding-agent", UpstreamPath: "adrenaline", Strengths: []string{"context indexing", "early repo Q&A workflow"}, Noteworthy: []string{"Historically important precursor for repository-grounded chat."}, AssimilationPlan: []string{"Mine prompt and repo-grounding ideas rather than clone UX."}},
		{ID: "auggie", DisplayName: "Auggie", Language: "TypeScript", Category: "coding-agent", UpstreamPath: "auggie", Strengths: []string{"editor-facing assistance", "repo context"}, Noteworthy: []string{"Useful reference for augmentation workflows and user prompts."}, AssimilationPlan: []string{"Extract interaction patterns and command ergonomics."}},
		{ID: "azure-ai-cli", DisplayName: "Azure AI CLI", Language: "TypeScript", Category: "provider", UpstreamPath: "azure-ai-cli", Strengths: []string{"commercial cloud integration", "deployment flows", "Azure auth"}, Noteworthy: []string{"Useful as provider and deployment surface, not as agent core."}, AssimilationPlan: []string{"Bridge Azure-specific provider and deployment tasks through TormentNexus."}},
		{ID: "bito", DisplayName: "Bito CLI", Language: "Shell/TypeScript", Category: "memory", UpstreamPath: "bito-cli", Strengths: []string{"workflow context", "review assistance"}, Noteworthy: []string{"Interesting emphasis on engineering context layer."}, AssimilationPlan: []string{"Assimilate contextual review prompts and workflow memory concepts."}},
		{ID: "byterover", DisplayName: "ByteRover CLI", Language: "TypeScript", Category: "memory", UpstreamPath: "byterover-cli", Strengths: []string{"portable memory", "retrieval workflows", "agent memory curation"}, Noteworthy: []string{"Important reference for persistent memory portability between sessions and tools."}, AssimilationPlan: []string{"Use TormentNexus memory as substrate, add ByteRover-style curation views and export/import semantics."}},
		{ID: "claude-code", DisplayName: "Claude Code mirror", Language: "TypeScript", Category: "coding-agent", UpstreamPath: "claude-code", Strengths: []string{"popular agent ergonomics", "tool-based coding workflow"}, Noteworthy: []string{"Use only as behavior reference; keep implementation clean-room and lawful."}, AssimilationPlan: []string{"Observe public UX patterns and command conventions only."}},
		{ID: "claude-code-templates", DisplayName: "Claude Code Templates", Language: "Markdown/TypeScript", Category: "prompts", UpstreamPath: "claude-code-templates", Strengths: []string{"workflow templates", "structured prompts"}, Noteworthy: []string{"Good prompt-template library input rather than core runtime logic."}, AssimilationPlan: []string{"Translate reusable workflows into prompt template packs."}},
		{ID: "code-cli", DisplayName: "Code CLI", Language: "TypeScript", Category: "coding-agent", UpstreamPath: "code-cli", Strengths: []string{"Codex-style harness compatibility"}, Noteworthy: []string{"Valuable for exact tool-harness compatibility expectations."}, AssimilationPlan: []string{"Cross-check tool naming, transport, and JSON surfaces for Codex-trained behavior."}},
		{ID: "copilot-cli", DisplayName: "GitHub Copilot CLI", Language: "TypeScript", Category: "coding-agent", UpstreamPath: "copilot-cli", Strengths: []string{"official subscription integration", "shell ergonomics"}, Noteworthy: []string{"Important for OAuth/subscription bridging and commercial familiarity."}, AssimilationPlan: []string{"Bridge auth and import session history, emulate stable shell-oriented affordances."}},
		{ID: "crush", DisplayName: "Crush", Language: "Go", Category: "tui", UpstreamPath: "crush", Strengths: []string{"Charm-powered UX", "fluid terminal interaction"}, Noteworthy: []string{"Best aesthetic benchmark for a Go-native TUI."}, AssimilationPlan: []string{"Borrow TUI patterns and interaction density, not wholesale code."}},
		{ID: "dolt", DisplayName: "Dolt", Language: "Go", Category: "storage", UpstreamPath: "dolt", Strengths: []string{"versioned SQL", "branching and merging data"}, Noteworthy: []string{"Potential future substrate for auditable memory/session state."}, AssimilationPlan: []string{"Study for versioned memory and operator audit history."}},
		{ID: "factory", DisplayName: "Factory Droid", Language: "TypeScript", Category: "orchestrator", UpstreamPath: "factory-cli", Strengths: []string{"persistent autonomous workflows", "verification", "multi-surface sessions"}, Noteworthy: []string{"Strongest reference for long-running background work and verify loops."}, AssimilationPlan: []string{"Assimilate persistence, background sessions, and verification workflows into the Go orchestration layer."}},
		{ID: "gemini-cli", DisplayName: "Gemini CLI", Language: "TypeScript", Category: "provider", UpstreamPath: "gemini-cli", Strengths: []string{"Google auth integration", "strong coding models"}, Noteworthy: []string{"Important subscription/provider compatibility target."}, AssimilationPlan: []string{"Bridge auth/session import via TormentNexus; mirror public model/provider affordances."}},
		{ID: "goose", DisplayName: "Goose", Language: "Rust", Category: "agent-core", UpstreamPath: "goose", Strengths: []string{"clean architecture", "protocol orientation", "performance"}, Noteworthy: []string{"One of the best references for a serious agent core, despite different language choice."}, AssimilationPlan: []string{"Adopt its protocol and layering discipline in Go."}},
		{ID: "grok-cli", DisplayName: "Grok CLI", Language: "TypeScript", Category: "agent-core", UpstreamPath: "grok-cli", Strengths: []string{"sub-agents", "batch mode", "remote control", "verify"}, Noteworthy: []string{"Unique remote-control and multi-agent delegation model."}, AssimilationPlan: []string{"Assimilate delegation and remote-control abstractions behind native Go command and session services."}},
		{ID: "jules", DisplayName: "Jules extension", Language: "TypeScript", Category: "extension", UpstreamPath: "jules-extension", Strengths: []string{"Gemini workflow integration"}, Noteworthy: []string{"Useful as extension/workflow signal, not as base runtime."}, AssimilationPlan: []string{"Translate into provider- and workflow-specific skill packs."}},
		{ID: "kilocode", DisplayName: "Kilo Code", Language: "TypeScript", Category: "agent-core", UpstreamPath: "kilocode", Strengths: []string{"high-volume autonomous engineering", "popular open source coding agent"}, Noteworthy: []string{"Good benchmark for task decomposition and throughput."}, AssimilationPlan: []string{"Mine orchestration and model defaults for autonomous modes."}},
		{ID: "kimi", DisplayName: "Kimi CLI", Language: "TypeScript", Category: "provider", UpstreamPath: "kimi-cli", Strengths: []string{"long-context coding models"}, Noteworthy: []string{"Important provider-specific tuning reference."}, AssimilationPlan: []string{"Add first-class provider/model profiles rather than one generic abstraction."}},
		{ID: "llm", DisplayName: "LLM CLI", Language: "Python", Category: "utility", UpstreamPath: "llm-cli", Strengths: []string{"Unix composability", "plugin ecosystem", "simple invocation model"}, Noteworthy: []string{"A model of restraint; worth emulating for shell mode and scripting."}, AssimilationPlan: []string{"Assimilate scriptability and plugin ergonomics into the Go CLI."}},
		{ID: "litellm", DisplayName: "LiteLLM", Language: "Python", Category: "provider-router", UpstreamPath: "litellm", Strengths: []string{"provider normalization", "OpenAI-compatible proxy", "routing"}, Noteworthy: []string{"TormentNexus already overlaps heavily here."}, AssimilationPlan: []string{"Use TormentNexus routing rather than reimplement; assimilate only missing provider-normalization details."}},
		{ID: "llamafile", DisplayName: "Llamafile", Language: "C/C++", Category: "runtime", UpstreamPath: "llamafile", Strengths: []string{"single-file local model delivery"}, Noteworthy: []string{"Important for local-runtime distribution strategy."}, AssimilationPlan: []string{"Treat as runtime target and packaging integration, not harness core."}},
		{ID: "mistral-vibe", DisplayName: "Mistral Vibe", Language: "Python", Category: "agent-core", UpstreamPath: "mistral-vibe", Strengths: []string{"minimal coding agent", "fast startup"}, Noteworthy: []string{"Useful benchmark for keeping the new core small."}, AssimilationPlan: []string{"Keep default harness minimal even while adding powerful optional layers."}},
		{ID: "ollama", DisplayName: "Ollama", Language: "Go", Category: "runtime", UpstreamPath: "ollama", Strengths: []string{"local model serving", "single binary distribution", "provider API"}, Noteworthy: []string{"Natural local runtime complement for a Go-native harness."}, AssimilationPlan: []string{"Integrate as first-class local provider target through TormentNexus/provider abstractions."}},
		{ID: "open-interpreter", DisplayName: "Open Interpreter", Language: "Python", Category: "computer-use", UpstreamPath: "open-interpreter", Strengths: []string{"computer control", "desktop automation", "OS integration"}, Noteworthy: []string{"Best reference for computer-use and local action layers."}, AssimilationPlan: []string{"Assimilate computer-use capabilities behind explicit trust boundaries and sandbox policies."}},
		{ID: "opencode", DisplayName: "OpenCode", Language: "TypeScript/Bun", Category: "agent-platform", UpstreamPath: "opencode", Strengths: []string{"rich TUI", "client/server split", "provider agnosticism"}, Noteworthy: []string{"Primary competitive benchmark for UX, extensibility, and reach."}, AssimilationPlan: []string{"Beat on startup speed, context accuracy, and trust while matching core UX expectations."}},
		{ID: "qwen-code", DisplayName: "Qwen Code CLI", Language: "TypeScript", Category: "provider", UpstreamPath: "qwen-code-cli", Strengths: []string{"Qwen-specific tuning"}, Noteworthy: []string{"Provider profile reference more than architecture reference."}, AssimilationPlan: []string{"Represent as provider preset and prompt profile."}},
		{ID: "rowboat", DisplayName: "Rowboat", Language: "TypeScript", Category: "repository-analysis", UpstreamPath: "rowboat", Strengths: []string{"repo exploration", "Q&A over codebases"}, Noteworthy: []string{"Useful lens on browse/explain workflows."}, AssimilationPlan: []string{"Assimilate explain/browse workflows into read-only analysis mode."}},
		{ID: "smithery", DisplayName: "Smithery CLI", Language: "TypeScript", Category: "ecosystem", UpstreamPath: "smithery-cli", Strengths: []string{"MCP discovery and installation"}, Noteworthy: []string{"Natural complement to TormentNexus's MCP control plane."}, AssimilationPlan: []string{"Use TormentNexus for runtime truth, assimilate Smithery-style discovery and install UX."}},
	}

	sort.Slice(items, func(i, j int) bool {
		return items[i].ID < items[j].ID
	})
	return items
}
