#!/usr/bin/env python3
"""
TormentNexus Swarm v7 - THE VERIFIED ASSIMILATOR
=================================================
3-model verification pipeline: Generate -> Review (x2) -> Fix

Every generated file is:
1. GENERATED by one model
2. REVIEWED by 2 independent models for compilation errors
3. FIXED by a third model if any reviewer found errors
4. Only written to disk if it passes review or is successfully fixed
"""

import argparse
import json
import os
import re
import signal
import sqlite3
import subprocess
import sys
import textwrap

# Configure streams to use UTF-8 under Windows to prevent charmap codec crashes
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")
import threading
import time
import traceback
import tempfile
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

# === CONFIG ===
PROXY_URL = os.environ.get("SWARM_PROXY", "http://localhost:4000/api/proxy")
PROXY_KEY = os.environ.get("SWARM_KEY", "sk-freellm")
PROXY_BIN = os.environ.get(
    "SWARM_PROXY_BIN", "C:/Users/hyper/workspace/freellm/freellm.exe"
)
WORKSPACE = Path(
    os.environ.get("SWARM_WORKSPACE", "C:/Users/hyper/workspace/tormentnexus")
)
GO_DIR = WORKSPACE / "go"
TOOLS_DIR = GO_DIR / "internal" / "tools"
REGISTRY_FILE = TOOLS_DIR / "registry.go"
DB_PATH = WORKSPACE / "data" / "assimilation_state.db"
MANIFEST_DIR = TOOLS_DIR / "manifests"

PROTECTED_FILES = {
    "registry.go",
    "parity.go",
    "factory.go",
    "basic_memory.go",
    "filesystem.go",
    "web_fetch.go",
    "sqlite.go",
    "bash.go",
    "glob.go",
    "apply_patch.go",
    "multi_edit.go",
    "git_ingest.go",
    # Core handler files (will compile in root build)
    "ddg_search.go",
    "gitingest.go",
    "sqlite.go",
    "search_tools.go",
    "skill_registry.go",
    "harnesses.go",
    "filesystem.go",
    "bash.go",
    "fetch.go",
    "ollama.go",
    "tts.go",
    "nws_tools.go",
    "nws_weather.go",
    "playwright_browser.go",
    "semgrep.go",
    "puppeteer.go",
    "prompt_library.go",
    "ripgrep.go",
}

# === MULTI-PROVIDER CONFIG (ALL VIA FREELLM PROXY) ===
# All connections go through the FreeLLM proxy at localhost:4000
# We use diverse model names to let the proxy spread load across backends.
# Each "provider" is a proxy slot with a different model alias.

PROXY_BASE = f"{PROXY_URL}/v1/chat/completions"

DIRECT_PROVIDERS = []

# PRIMARY: freellm proxy (localhost:4000) — waits indefinitely, never times out
for _model, _cd in [
    ("free-llm", 15),
]:
    DIRECT_PROVIDERS.append(
        {
            "name": f"freellm-{_model.replace('/', '-').lower()}",
            "url": PROXY_BASE,
            "key": PROXY_KEY,
            "model": _model,
            "cooldown": _cd,
            "timeout": 3600,
            "stream": True,
        }
    )

# All pipeline phases use freellm only — waits indefinitely, never times out
GENERATOR_MODELS = ["free-llm"]
REVIEWER_MODELS = ["free-llm"]
FIXER_MODELS = ["free-llm"]

STREAM_TIMEOUT = 86400
CURL_TIMEOUT = 86400
CALL_COOLDOWN = 10  # Fast cycling — only one provider
PIPELINE_COOLDOWN = 5  # Fast pipeline
MAX_RETRIES = 999  # Wait indefinitely for freellm
RETRY_BASE_DELAY = 60  # Slow initial backoff
CIRCUIT_BREAKER_FAILS = 999
CIRCUIT_BREAKER_COOLDOWN = 10
MIN_CONTENT_LENGTH = 50  # Accept short responses, let them fail review naturally
BUILD_VERIFY_EVERY = 3
PROXY_RESTART_AFTER = 8


# === LOG ===
class Log:
    C = {
        "R": "\033[91m",
        "G": "\033[92m",
        "Y": "\033[93m",
        "B": "\033[94m",
        "M": "\033[95m",
        "C": "\033[96m",
        "0": "\033[0m",
    }

    def __init__(self, path=None):
        self.lock = threading.Lock()
        self.path = path
        self.t0 = time.time()
        self.ok_count = 0
        self.fail_count = 0
        self.llm_ok_count = 0
        self.llm_err_count = 0
        self.builds_ok = 0
        self.builds_fix = 0
        self.model_stats = {}
        self.phase_stats = {
            "gen_ok": 0,
            "gen_err": 0,
            "rev_ok": 0,
            "rev_err": 0,
            "fix_ok": 0,
            "fix_err": 0,
            "fix_needed": 0,
            "fix_compile_ok": 0,
            "fix_compile_err": 0,
            "rev_agreed": 0,
        }

    def _ts(self):
        e = int(time.time() - self.t0)
        return f"{e // 3600:02d}:{(e % 3600) // 60:02d}:{e % 60:02d}"

    def _w(self, lvl, col, wid, msg):
        p = (
            f"[{self._ts()}]"
            + (f"[W{wid}]" if wid is not None else "")
            + f"[{lvl}] {msg}"
        )
        with self.lock:
            print(f"{self.C.get(col, '')}{p}{self.C['0']}", flush=True)
            if self.path:
                try:
                    with open(self.path, "a", encoding="utf-8", errors="replace") as f:
                        f.write(p + "\n")
                except:
                    pass

    def info(self, m, w=None):
        self._w("INFO", "C", w, m)

    def ok(self, m, w=None):
        self._w("OK", "G", w, m)
        self._inc("ok_count")

    def warn(self, m, w=None):
        self._w("WARN", "Y", w, m)

    def err(self, m, w=None):
        self._w("ERR", "R", w, m)
        self._inc("fail_count")

    def llm(self, m, w=None):
        self._w("LLM", "M", w, m)
        self._inc("llm_ok_count")

    def llm_fail(self, m, w=None):
        self._w("LLM-ERR", "R", w, m)
        # self._inc("llm_err_count")  # disabled

    def phase(self, m, w=None):
        self._w("PHASE", "B", w, m)

    def stat(self, m):
        self._w("STAT", "B", None, m)

    def build(self, m):
        self._w("BUILD", "B", None, m)

    def _inc(self, k):
        with self.lock:
            setattr(self, k, getattr(self, k) + 1)

    def record_model(self, model, ok, chars=0):
        with self.lock:
            s = self.model_stats.setdefault(model, {"ok": 0, "err": 0, "chars": 0})
            if ok:
                s["ok"] += 1
                s["chars"] += chars
            else:
                s["err"] += 1

    def record_phase(self, phase, ok):
        with self.lock:
            k = f"{phase}_ok" if ok else f"{phase}_err"
            if k in self.phase_stats:
                self.phase_stats[k] += 1

    def summary(self):
        e = int(time.time() - self.t0)
        with self.lock:
            ps = self.phase_stats
            s = (
                f"ok={self.ok_count} fail={self.fail_count} "
                f"llm_ok={self.llm_ok_count} llm_err={self.llm_err_count} "
                f"gen={ps['gen_ok']}/{ps['gen_err']} "
                f"rev={ps['rev_ok']}/{ps['rev_err']} "
                f"fix={ps['fix_ok']}/{ps['fix_err']} "
                f"fix_needed={ps['fix_needed']} rev_agree={ps['rev_agreed']} "
                f"elapsed={e // 3600}h{(e % 3600) // 60}m"
            )
            best = sorted(
                [(m, v["ok"]) for m, v in self.model_stats.items() if v["ok"] > 0],
                key=lambda x: x[1],
                reverse=True,
            )[:3]
            if best:
                s += " | best: " + ", ".join(f"{m}({o})" for m, o in best)
            return s


log = Log()


# === LLM CLIENT - MULTI-PROVIDER ===
BLACKLISTED_MODELS = set()


class LLMClient:
    def __init__(self):
        self.lock = threading.Lock()
        self.circuit_open = False
        self.circuit_opened_at = 0
        self.consecutive_fails = 0
        self.provider_idx = 0
        self.provider_last_call = {}
        self.provider_fails = {}
        self.provider_oks = {}
        # Global concurrency limiter for proxy calls
        self._llm_semaphore = threading.Semaphore(5)  # max 5 concurrent LLM requests

    def _next_provider(self):
        with self.lock:
            providers = DIRECT_PROVIDERS
            if not providers:
                return None
            now = time.time()
            for _ in range(len(providers)):
                p = providers[self.provider_idx % len(providers)]
                self.provider_idx += 1
                name = p["name"]
                cooldown = p.get("cooldown", 10)
                last = self.provider_last_call.get(name, 0)
                if now - last >= cooldown:
                    return p
            best = min(
                providers,
                key=lambda p: time.time() - self.provider_last_call.get(p["name"], 0),
            )
            return best

    def blacklist_model(self, model):
        BLACKLISTED_MODELS.add(model)
        log.warn(f"Blacklisted: {model} ({len(BLACKLISTED_MODELS)} total)")

    def _check_circuit(self):
        if not self.circuit_open:
            return True
        if time.time() - self.circuit_opened_at > CIRCUIT_BREAKER_COOLDOWN:
            log.stat("Circuit breaker reset")
            self.circuit_open = False
            self.consecutive_fails = 0
            return True
        return False

    def _trip_circuit(self):
        self.circuit_open = True
        self.circuit_opened_at = time.time()
        log.warn(f"Circuit OPEN - {CIRCUIT_BREAKER_COOLDOWN}s cooldown")

    def _record_fail(self, provider_name):
        self.consecutive_fails += 1
        self.provider_fails[provider_name] = (
            self.provider_fails.get(provider_name, 0) + 1
        )
        if self.consecutive_fails >= CIRCUIT_BREAKER_FAILS:
            self._trip_circuit()

    def _record_ok(self, provider_name):
        self.consecutive_fails = 0
        self.provider_fails[provider_name] = 0
        self.provider_oks[provider_name] = self.provider_oks.get(provider_name, 0) + 1

    def _wait_for_cooldown(self, provider):
        name = provider["name"]
        cooldown = provider.get("cooldown", 10)
        last = self.provider_last_call.get(name, 0)
        wait = cooldown - (time.time() - last)
        if wait > 0:
            time.sleep(wait)

    def call_provider(self, prompt, system, provider, wid=0):
        name = provider["name"]
        url = provider["url"]
        key = provider["key"]
        model = provider["model"]
        timeout = provider.get("timeout", 300)
        # Limit concurrent LLM calls to avoid overwhelming the proxy
        self._llm_semaphore.acquire()
        try:
            return self._call_provider_inner(prompt, system, provider, wid)
        finally:
            self._llm_semaphore.release()

    def _call_provider_inner(self, prompt, system, provider, wid=0):
        name = provider["name"]
        url = provider["url"]
        key = provider["key"]
        model = provider["model"]
        timeout = provider.get("timeout", 3600)
        self._wait_for_cooldown(provider)
        self.provider_last_call[name] = time.time()
        payload = json.dumps(
            {
                "model": model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.2,
                "max_tokens": 4096,
                "stream": True,
            }
        )
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False, encoding="utf-8"
        ) as tf:
            tf.write(payload)
            tf_path = tf.name
        t0 = time.time()
        log.llm(f"{name}/{model} t={timeout}s", wid)
        try:
            headers = ["-H", "Content-Type: application/json"]
            if key:
                headers += ["-H", f"Authorization: Bearer {key}"]
            result = subprocess.run(
                ["curl", "-s", "-N", "--max-time", str(timeout), "-X", "POST", url]
                + headers
                + ["--data", f"@{tf_path}"],
                capture_output=True,
                text=True,
                timeout=timeout + 30,
                encoding="utf-8",
                errors="replace",
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
            elapsed = time.time() - t0
            # Parse SSE stream from proxy
            content = ""
            model_used = ""
            for line in result.stdout.split("\n"):
                line = line.strip()
                if line.startswith("data: ") and line != "data: [DONE]":
                    try:
                        d = json.loads(line[6:])
                        if not model_used:
                            model_used = d.get("model", model)
                        c = (
                            d.get("choices", [{}])[0]
                            .get("delta", {})
                            .get("content", "")
                        )
                        if c:
                            content += c
                    except:
                        pass
            if content and len(content) >= MIN_CONTENT_LENGTH:
                self._record_ok(name)
                log.llm(f"{name}: {len(content)}c in {elapsed:.1f}s", wid)
                log.record_model(name, True, len(content))
                return content, name, elapsed
            log.llm_fail(
                f"{name}: short/empty ({len(content)}c in {elapsed:.1f}s)", wid
            )
            self._record_fail(name)
            log.record_model(name, False)
            return None, name, elapsed
        except subprocess.TimeoutExpired:
            elapsed = time.time() - t0
            log.llm_fail(f"{name}: timeout", wid)
            self._record_fail(name)
            return None, name, elapsed
        except Exception as e:
            elapsed = time.time() - t0
            log.llm_fail(f"{name}: {str(e)[:120]}", wid)
            self._record_fail(name)
            return None, name, elapsed
        finally:
            try:
                os.unlink(tf_path)
            except:
                pass

    def call(self, prompt, system="", phase="gen", wid=0, max_retries=None):
        if not self._check_circuit():
            return None
        retries = max_retries or MAX_RETRIES
        for attempt in range(retries):
            if self.circuit_open:
                time.sleep(CIRCUIT_BREAKER_COOLDOWN)
                if not self._check_circuit():
                    continue
            provider = self._next_provider()
            if not provider:
                log.warn("No providers available!", wid)
                time.sleep(30)
                continue
            content, pname, elapsed = self.call_provider(prompt, system, provider, wid)
            if content:
                return content
            delay = RETRY_BASE_DELAY * (2 ** min(attempt, 3))
            log.warn(
                f"Retry {attempt + 1}/{retries} after {delay}s (provider: {pname})", wid
            )
            time.sleep(delay)
        log.err(f"All {retries} retries exhausted", wid)
        return None


llm = LLMClient()


# === PROXY MANAGER ===
class ProxyManager:
    def __init__(self):
        self._healthy = True

    def check(self):
        for attempt in range(3):
            try:
                import urllib.request

                with urllib.request.urlopen(f"{PROXY_URL}/v1/models", timeout=5) as r:
                    if r.status == 200:
                        self._healthy = True
                        return True
            except:
                if attempt < 2:
                    time.sleep(2)
        self._healthy = False
        return False

    def restart(self):
        log.stat("Restarting proxy...")
        try:
            subprocess.run(
                ["taskkill", "/F", "/IM", "freellm.exe"],
                capture_output=True,
                timeout=10,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
        except Exception as e:
            log.warn(f"taskkill failed: {e}")
        time.sleep(5)
        try:
            normalized_bin = os.path.normpath(PROXY_BIN)
            d = os.path.dirname(normalized_bin)
            log.stat(f"Spawning proxy: {normalized_bin} in cwd: {d}")
            subprocess.Popen(
                [normalized_bin],
                cwd=d,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                creationflags=subprocess.CREATE_NO_WINDOW,
            )
        except Exception as e:
            log.err(f"Proxy start: {e}")
            return False
        for i in range(24):
            time.sleep(5)
            if self.check():
                log.ok("Proxy back up!")
                return True
        log.err("Proxy never came up")
        return False

    @property
    def healthy(self):
        return self._healthy


proxy = ProxyManager()


# === GO CODE EXTRACTION ===
def extract_go_code(content, go_filename):
    if not content:
        return None, None
    go_code = manifest = None
    gm = re.search(r"===GO_FILE===\s*\n(.*?)(?====MANIFEST===|$)", content, re.DOTALL)
    mm = re.search(r"===MANIFEST===\s*\n(.*?)$", content, re.DOTALL)
    if gm:
        go_code = _strip_fences(gm.group(1).strip())
        if mm:
            manifest = _parse_manifest(mm.group(1).strip(), go_filename)
    if go_code and _has_handlers(go_code):
        if not go_code.strip().startswith("package tools"):
            go_code = _extract_from_mixed(go_code)
        go_code = fix_truncated_code(go_code)
        return go_code, manifest
    blocks = re.findall(r"```go\s*\n(.*?)```", content, re.DOTALL)
    if blocks:
        go_code = _assemble_from_blocks(blocks)
        if go_code and _has_handlers(go_code):
            if not manifest:
                manifest = _build_manifest_from_code(go_code, go_filename)
            return go_code, manifest
    idx = content.find("package tools")
    if idx >= 0:
        go_code = _clean_raw_code(content[idx:])
        if go_code and _has_handlers(go_code):
            if not manifest:
                manifest = _build_manifest_from_code(go_code, go_filename)
            return go_code, manifest
    parts = [
        m.group(0)
        for m in re.finditer(
            r"func Handle\w+\s*\([^)]*\)\s*\([^)]*\)\s*\{.*?\n\}", content, re.DOTALL
        )
    ]
    if parts:
        go_code = (
            'package tools\n\nimport (\n\t"context"\n\t"encoding/json"\n\t"fmt"\n\t"io"\n\t"net/http"\n\t"net/url"\n\t"os"\n\t"time"\n)\n\n'
            + "\n\n".join(parts)
        )
        manifest = _build_manifest_from_code(go_code, go_filename)
        return go_code, manifest
    return None, None


def sanitize_go_code(code):
    """Delegate to the external sanitize_go module."""
    from sanitize_go import sanitize_go_code as _sanitize

    return _sanitize(code)


def _strip_fences(code):
    code = re.sub(r"^```go\s*\n?", "", code)
    code = re.sub(r"\n?```\s*$", "", code)
    return code.strip()


def _has_handlers(code):
    return bool(re.search(r"func Handle\w+\s*\(", code))


def _parse_manifest(raw, go_filename):
    raw = _strip_fences(raw)
    try:
        return json.loads(raw)
    except:
        pass
    fixed = re.sub(r",\s*}", "}", raw)
    fixed = re.sub(r",\s*]", "]", fixed)
    try:
        return json.loads(fixed)
    except:
        return None


def _assemble_from_blocks(blocks):
    code_blocks = [b.strip() for b in blocks if b.strip()]
    if not code_blocks:
        return None
    for block in code_blocks:
        if "package tools" in block and _has_handlers(block):
            return block
    base = None
    additions = []
    for block in code_blocks:
        if "package tools" in block:
            base = block
        elif _has_handlers(block) or re.match(r"(type|var|const)\s", block):
            additions.append(block)
    if base:
        for add in additions:
            if add not in base:
                fh = re.search(r"func Handle\w+", base)
                if fh:
                    base = base[: fh.start()] + add + "\n\n" + base[fh.start() :]
                else:
                    base += "\n\n" + add
        return base
    if additions:
        imports = set()
        for block in additions:
            for imp in re.findall(r'"([^"]+)"', block):
                if "/" not in imp or imp.startswith("golang.org"):
                    imports.add(imp)
        imp_block = (
            ("import (\n" + "\n".join(f'\t"{i}"' for i in sorted(imports)) + "\n)\n\n")
            if imports
            else ""
        )
        code = "package tools\n\n" + imp_block + "\n\n".join(additions)
        if _has_handlers(code):
            return code
    return None


def _extract_from_mixed(code):
    idx = code.find("package tools")
    if idx < 0:
        return None
    return _clean_raw_code(code[idx:])


def _clean_raw_code(code):
    lines = code.split("\n")
    clean = []
    in_code = False
    skip = False
    for line in lines:
        s = line.strip()
        if re.match(r"^\d+\.\s+\*\*", s):
            skip = True
            continue
        if re.match(r"^[*\-]\s+\*\*", s):
            skip = True
            continue
        if skip:
            if s.startswith(
                ("package ", "import ", "func ", "type ", "var ", "const ", "//")
            ) or (s == "" and in_code):
                skip = False
            else:
                continue
        if s.startswith("package tools"):
            in_code = True
        if in_code:
            clean.append(line)
    result = "\n".join(clean)
    return result if _has_handlers(result) else None


def fix_truncated_code(code):
    if not code:
        return code
    lines = code.rstrip().split("\n")
    while lines:
        s = lines[-1].strip()
        if not s:
            break
        if re.search(r"[;,{}()\[\]]\s*$", s) or s.endswith(")"):
            break
        lines.pop()
    code = "\n".join(lines)
    open_b = code.count("{") - code.count("}")
    if open_b > 0:
        for i in range(open_b):
            code += "\n" + "\t" * max(0, open_b - i - 1) + "}"
    for hm in re.finditer(r"func (Handle\w+)\s*\([^)]*\)\s*\([^)]*\)\s*\{", code):
        start = hm.end()
        depth = 1
        end = start
        for i in range(start, len(code)):
            if code[i] == "{":
                depth += 1
            elif code[i] == "}":
                depth -= 1
            if depth == 0:
                end = i
                break
        body = code[start:end]
        if "return ok(" not in body and "return err(" not in body:
            lb = code.rfind("}", start, end + 1)
            if lb > 0:
                code = code[:lb] + '\n\treturn ok("not yet implemented")\n' + code[lb:]
                break
    return code


def _build_manifest_from_code(code, go_filename):
    handlers = re.findall(r"func (Handle\w+)\s*\(", code)
    return {
        "filename": f"{go_filename}.go",
        "handlers": [
            {
                "tool_name": re.sub(r"([A-Z])", r"_\1", h[6:]).lower().lstrip("_"),
                "handler_func": h,
                "description": h,
            }
            for h in handlers
        ],
    }


# === REVIEW PARSER ===
def parse_review(content):
    if not content:
        return False, ["empty review"]
    jm = re.search(r'\{[^{}]*"compiles"\s*:\s*(true|false)[^{}]*\}', content, re.DOTALL)
    if jm:
        try:
            d = json.loads(jm.group(0))
            return d.get("compiles", False), d.get("errors", [])
        except:
            pass
    cl = content.lower()
    if '"compiles": true' in cl or '"compiles":true' in cl:
        return True, []
    if '"compiles": false' in cl or '"compiles":false' in cl:
        errors = re.findall(r'"errors"\s*:\s*\[(.*?)\]', content, re.DOTALL)
        err_list = (
            re.findall(r'"([^"]+)"', errors[0]) if errors else ["reviewer found errors"]
        )
        return False, err_list
    return False, ["unparseable review"]


# === DATABASE ===
_db_lock = threading.Lock()


def claim_task(worker_id):
    with _db_lock:
        db = sqlite3.connect(str(DB_PATH))
        db.isolation_level = "EXCLUSIVE"
        c = db.cursor()
        row = c.execute(
            "SELECT name, github_url, score FROM mcp_servers WHERE status='pending' ORDER BY score DESC LIMIT 1"
        ).fetchone()
        if not row:
            db.close()
            return None
        name = row[0]
        c.execute(
            "UPDATE mcp_servers SET status='processing', notes=?, updated_at=CURRENT_TIMESTAMP WHERE name=? AND status='pending'",
            (f"v7-w{worker_id}", name),
        )
        db.commit()
        if c.rowcount == 0:
            db.close()
            return None
        db.close()
        return {
            "name": name,
            "github_url": row[1] or "",
            "score": row[2] or 0,
            "category": "unknown",
            "description": "",
            "subcategory": "",
            "tags": "",
        }


def claim_implemented_task(worker_id):
    """Claim an implemented server for validation."""
    with _db_lock:
        db = sqlite3.connect(str(DB_PATH))
        db.isolation_level = "EXCLUSIVE"
        c = db.cursor()
        row = c.execute(
            "SELECT name, github_url FROM mcp_servers WHERE status='implemented' AND (notes IS NULL OR notes NOT LIKE 'validated%') ORDER BY RANDOM() LIMIT 1"
        ).fetchone()
        if not row:
            db.close()
            return None
        name = row[0]
        c.execute(
            "UPDATE mcp_servers SET notes=?, updated_at=CURRENT_TIMESTAMP WHERE name=? AND status='implemented'",
            (f"validating-v7-w{worker_id}", name),
        )
        db.commit()
        if c.rowcount == 0:
            db.close()
            return None
        db.close()
        return {"name": name, "github_url": row[1] or ""}


def record_validation(name, status, detail):
    """Record a validation result in the DB."""
    with _db_lock:
        db = sqlite3.connect(str(DB_PATH))
        c = db.cursor()
        # Append validation status to notes
        existing = c.execute(
            "SELECT notes FROM mcp_servers WHERE name=?", (name,)
        ).fetchone()
        notes = (existing[0] or "") if existing else ""
        # Remove old validation marker
        notes = re.sub(r"validated-\S+", "", notes).strip()
        new_notes = f"{notes} validated-{status}:{detail[:60]}".strip()
        c.execute(
            "UPDATE mcp_servers SET notes=?, updated_at=CURRENT_TIMESTAMP WHERE name=?",
            (new_notes, name),
        )
        db.commit()
        db.close()


def complete_task(name, go_file, tools_count, review_status=""):
    with _db_lock:
        db = sqlite3.connect(str(DB_PATH))
        c = db.cursor()
        c.execute(
            "UPDATE mcp_servers SET status='implemented', go_file=?, tools_exposed=?, notes=?, updated_at=CURRENT_TIMESTAMP WHERE name=?",
            (go_file, str(tools_count), f"v7-{review_status}", name),
        )
        db.commit()
        db.close()


def fail_task(name, error=""):
    with _db_lock:
        db = sqlite3.connect(str(DB_PATH))
        c = db.cursor()
        c.execute(
            "UPDATE mcp_servers SET status='failed', notes=?, updated_at=CURRENT_TIMESTAMP WHERE name=?",
            (error[:500], name),
        )
        db.commit()
        db.close()


def release_task(name):
    with _db_lock:
        db = sqlite3.connect(str(DB_PATH))
        c = db.cursor()
        c.execute(
            "UPDATE mcp_servers SET status='pending', notes='released' WHERE name=? AND status='processing'",
            (name,),
        )
        db.commit()
        db.close()


def reset_stale():
    db = sqlite3.connect(str(DB_PATH))
    c = db.cursor()
    c.execute(
        "UPDATE mcp_servers SET status='pending', notes='stale' WHERE status='processing'"
    )
    n = c.rowcount
    db.commit()
    db.close()
    return n


def reset_failed(limit=30, min_score=0):
    db = sqlite3.connect(str(DB_PATH))
    c = db.cursor()
    # SQLite doesn't support ORDER BY/LIMIT in UPDATE on all versions
    # First get the names, then update by name
    c.execute(
        "SELECT name FROM mcp_servers WHERE status='failed' AND score >= ? ORDER BY score DESC LIMIT ?",
        (min_score, limit),
    )
    names = [row[0] for row in c.fetchall()]
    if names:
        placeholders = ",".join(["?"] * len(names))
        c.execute(
            f"UPDATE mcp_servers SET status='pending', notes='retry' WHERE name IN ({placeholders})",
            names,
        )
    n = c.rowcount
    db.commit()
    db.close()
    return n


def get_stats():
    db = sqlite3.connect(str(DB_PATH))
    c = db.cursor()
    t = c.execute("SELECT COUNT(*) FROM mcp_servers").fetchone()[0]
    i = c.execute(
        'SELECT COUNT(*) FROM mcp_servers WHERE status="implemented"'
    ).fetchone()[0]
    p = c.execute('SELECT COUNT(*) FROM mcp_servers WHERE status="pending"').fetchone()[
        0
    ]
    f = c.execute('SELECT COUNT(*) FROM mcp_servers WHERE status="failed"').fetchone()[
        0
    ]
    db.close()
    return t, i, p, f


# === FILE NAMING & PROMPTS ===
def name_to_filename(name):
    n = name
    for p in ["mcp-server-", "mcp-", "@", "server-", "mcp_"]:
        if n.lower().startswith(p):
            n = n[len(p) :]
    n = re.sub(r"[/.\-]+", "_", n)
    n = re.sub(r"[^a-zA-Z0-9_]", "", n).lower()
    if len(n) < 2:
        n = f"tool_{abs(hash(name)) % 10000}"
    return n[:60]


def make_gen_prompt(task, sources=None):
    n = task["name"]
    u = task.get("github_url", "")
    d = task.get("description", "")
    cat = task.get("category", "")
    fn = name_to_filename(n)

    # Include original source code in prompt if available
    source_section = ""
    if sources:
        source_section = (
            "\n\nORIGINAL MCP SERVER SOURCE CODE (reimplement this in Go):\n"
        )
        for fname in sorted(sources.keys()):
            content = sources[fname][:8000]
            if content.strip():
                source_section += f"\n--- {fname} ---\n{content}\n"
        source_section = source_section[:20000]

    prompt = textwrap.dedent(f"""\
Implement a Go-native MCP tool module for "{n}".
GitHub: {u} | Category: {cat} | Description: {d}{source_section}
CRITICAL: Study the original MCP server source code above and faithfully reimplement EVERY tool/function in Go.
RULES:
1. Package: package tools
2. Handler: func HandleXxx(ctx context.Context, args map[string]interface{{}}) (ToolResponse, error)
3. Success: return ok("text") - ok() returns (ToolResponse, error)
4. Error CHECK: if e != nil {{ return err(e.Error()) }}
5. getString/getInt/getBool return SINGLE values: val := getString(args, "key")
6. ONLY stdlib imports: context, encoding/json, fmt, io, net/http, net/url, os, os/exec, path/filepath, strconv, strings, time, regexp, sort
7. http.Client{{Timeout: 30*time.Second}}
8. 2-6 handlers, keep simple, MUST COMPILE, no TODOs
9. Do NOT redeclare ToolResponse, ok, err, getString, getInt, getBool, TextContent - they exist in parity.go
10. NO external packages (no github.com imports)
11. COMMON BUGS TO AVOID:
    - NEVER redeclare a variable named "err" — it shadows the err() function from parity.go. Use different names like "apiErr", "fetchErr", "parseErr"
    - ALWAYS import ALL packages you use: "time", "strings", "net/url", "regexp", "sort" are NOT automatic
    - EVERY function MUST end with a return statement (return ok(...) or return err(...))
    - Do NOT use url.QueryEscape — use net/url's url.Values instead
    - If you use "regexp", import "regexp" and compile with regexp.MustCompile
12. Use specific variable names (apiErr, fetchErr, parseErr, reqErr) instead of generic "err" to avoid shadowing
OUTPUT FORMAT - output TWO sections:
===GO_FILE===
package tools // complete Go source code
===MANIFEST===
{{"filename":"{fn}.go","server_name":"{n}","handlers":[{{"tool_name":"x","handler_func":"HandleX","description":"d"}}]}}""")
    system = textwrap.dedent("""\
You write clean compilable Go code for MCP tool handlers.
ok()/err() return (ToolResponse, error). getString returns single value.
No pseudocode, no TODOs. Every function MUST compile.
Do NOT redeclare types from parity.go. NO external packages.
Output ===GO_FILE=== then code, then ===MANIFEST=== then JSON.""")
    return prompt, system


def fetch_source_code(github_url, temp_dir):
    """Download original MCP server source code to a temp directory.
    Returns dict of {filename: content} for key source files."""
    sources = {}
    if not github_url or "github.com" not in github_url:
        return sources

    repo_url = github_url.rstrip("/")
    if repo_url.startswith("git+"):
        repo_url = repo_url[4:]
    if repo_url.startswith("git@"):
        repo_url = "https://" + repo_url.split("@")[1].replace(":", "/")
    if repo_url.endswith(".git"):
        repo_url = repo_url[:-4]

    repo_name = repo_url.split("/")[-1]
    dest = os.path.join(temp_dir, repo_name)

    # Try shallow clone first
    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", "--single-branch", repo_url, dest],
            capture_output=True,
            text=True,
            timeout=60,
            creationflags=subprocess.CREATE_NO_WINDOW,
        )
    except Exception:
        # Fall back to raw file fetching
        raw_base = repo_url.replace("github.com", "raw.githubusercontent.com")
        for branch in ["main", "master"]:
            for path in [
                "package.json",
                "mcp.json",
                "index.ts",
                "index.js",
                "server.ts",
                "server.py",
                "src/index.ts",
                "src/index.js",
                "src/server.ts",
                "src/server.py",
            ]:
                try:
                    req = urllib.request.Request(
                        f"{raw_base}/{branch}/{path}",
                        headers={"User-Agent": "Mozilla/5.0"},
                    )
                    with urllib.request.urlopen(req, timeout=15) as r:
                        content = r.read().decode("utf-8", errors="replace")
                        if content.strip():
                            sources[path] = content[:15000]
                except Exception:
                    continue
            if sources:
                break
        return sources

    # Read key source files from cloned repo
    if os.path.isdir(dest):
        ext_patterns = (".ts", ".js", ".py", ".json", ".md")
        for root, dirs, files in os.walk(dest):
            # Skip node_modules, .git, dist
            dirs[:] = [
                d
                for d in dirs
                if d not in ("node_modules", ".git", "dist", ".next", "build")
            ]
            for fn in files:
                if (
                    fn.endswith(ext_patterns)
                    and os.path.getsize(os.path.join(root, fn)) < 50000
                ):
                    rel = os.path.relpath(os.path.join(root, fn), dest)
                    try:
                        with open(
                            os.path.join(root, fn),
                            "r",
                            encoding="utf-8",
                            errors="replace",
                        ) as f:
                            sources[rel] = f.read()[:15000]
                    except Exception:
                        pass

    return sources


def make_review_prompt(go_code):
    prompt = textwrap.dedent(f"""\
Review this Go code for compilation errors. These are pre-defined in parity.go:
- type ToolResponse struct {{}}
- func ok(text string) (ToolResponse, error)
- func err(msg string) (ToolResponse, error)
- func getString(args map[string]interface{{}}, key string) string
- func getInt(args map[string]interface{{}}, key string) int
- func getBool(args map[string]interface{{}}, key string) bool
- type TextContent struct {{}}

Check for: 1) missing/unused imports 2) undefined types/functions (except above) 3) wrong signatures 4) missing returns 5) syntax errors 6) external imports (only stdlib) 7) redeclared parity.go types

Code:
```go
{go_code}
```

Respond with ONLY this JSON:
{{"compiles": true_or_false, "errors": ["error1", "error2"], "fixes_needed": true_or_false}}""")
    system = "You are a Go compiler expert. Respond with ONLY JSON. No explanation."
    return prompt, system


def make_fix_prompt(go_code, errors):
    err_text = "\n".join(f"- {e}" for e in errors)
    prompt = textwrap.dedent(f"""\
Fix ALL compilation errors in this Go code.

PRE-DEFINED in parity.go (do NOT redeclare):
- type ToolResponse, func ok(), func err(), func getString(), func getInt(), func getBool(), type TextContent

ERRORS FOUND BY REVIEWERS:
{err_text}

RULES:
1. package tools
2. func HandleXxx(ctx context.Context, args map[string]interface{{}}) (ToolResponse, error)
3. return ok("text"), if e != nil {{ return err(e.Error()) }}
4. getString returns single value
5. ONLY stdlib imports (no github.com)
6. Must compile - no TODOs

Original code:
```go
{go_code}
```

Output the COMPLETE fixed code. No explanation. No markdown. Start with 'package tools'.""")
    system = "Output ONLY fixed Go code starting with 'package tools'. No explanation. No markdown."
    return prompt, system


# === BUILD VERIFICATION ===
def verify_build():
    try:
        r = subprocess.run(
            ["go", "build", "-buildvcs=false", "./cmd/tormentnexus"],
            capture_output=True,
            text=True,
            cwd=str(GO_DIR),
            timeout=120,
            encoding="utf-8",
            errors="replace",
            creationflags=subprocess.CREATE_NO_WINDOW,
        )
        if r.returncode == 0:
            log.build("CLEAN")
            log._inc("builds_ok")
            return True
        broken = set()
        undefs = set()
        for line in (r.stderr or "").split("\n"):
            for sep in ["internal\tools\\", "internal/tools/"]:
                if sep in line:
                    fname = line.split(sep, 1)[1].split(":")[0]
                    if fname.endswith(".go") and fname not in PROTECTED_FILES:
                        broken.add(fname)
                    break
            if "undefined:" in line:
                for w in line.split():
                    w = w.rstrip(",")
                    if w.startswith("Handle") and len(w) > 6:
                        undefs.add(w)
        for f in broken:
            p = TOOLS_DIR / f
            if p.exists():
                log.warn(f"Removing broken: {f}")
                p.unlink()
        if undefs:
            _clean_registry(undefs)
        log._inc("builds_fix")
        return False
    except Exception as e:
        log.err(f"Build error: {e}")
        return False


def _clean_registry(handlers):
    try:
        with open(REGISTRY_FILE, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        new = [l for l in lines if not any(h in l for h in handlers)]
        with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
            f.writelines(new)
        log.info(f"Cleaned {len(lines) - len(new)} undefined refs")
    except Exception as e:
        log.err(f"Registry clean: {e}")


def make_compile_fix_prompt(go_code, compile_errors):
    """Build a prompt that asks the LLM to fix actual Go compiler errors."""
    prompt = textwrap.dedent(f"""\
Fix ALL compilation errors in this Go code.

ACTUAL COMPILER ERRORS:
{compile_errors}

AVAILABLE TYPES (do NOT redeclare):
- ToolResponse, TextContent, ToolHandler
- func ok(text string) (ToolResponse, error)
- func err(msg string) (ToolResponse, error)
- func getString(args map[string]interface{{}}, key string) (string, bool)
- func getInt(args map[string]interface{{}}, key string) (int, bool)
- func getBool(args map[string]interface{{}}, key string) (bool, bool)

RULES:
1. package tools
2. func HandleXxx(ctx context.Context, args map[string]interface{{}}) (ToolResponse, error)
3. return ok(\"text\"), if e != nil {{ return err(e.Error()) }}
4. getString returns (string, bool) — check the bool!
5. ONLY stdlib imports (no github.com)
6. Must compile — no TODOs, no pseudocode
7. Every function body must be COMPLETE, no ellipsis or placeholders

The compiler says what's wrong. Fix ALL errors.

Code:
```go
{go_code}
```

Output the COMPLETE fixed Go code. Start with 'package tools'.""")
    system = "Output ONLY fixed Go code starting with 'package tools'. No explanation. No markdown."
    return prompt, system


def repair_build(max_iter=15):
    for i in range(max_iter):
        if verify_build():
            log.ok(f"Build clean (iter {i})")
            return True
        log.warn(f"Build broken, iter {i + 1}")
        time.sleep(1)
    return verify_build()


def _remove_external_imports():
    removed = 0
    for fn in os.listdir(str(TOOLS_DIR)):
        if fn.endswith(".go") and fn not in PROTECTED_FILES:
            with open(TOOLS_DIR / fn, "r", encoding="utf-8", errors="replace") as f:
                code = f.read()
            external = [
                imp
                for imp in re.findall(r'"([^"]+)"', code)
                if imp.startswith("github.com") and "tormentnexushq" not in imp
            ]
            if external:
                (TOOLS_DIR / fn).unlink()
                removed += 1
    return removed


# === MANIFEST MERGER ===
_merge_lock = threading.Lock()


def merge_manifests():
    with _merge_lock:
        if not MANIFEST_DIR.exists():
            return 0
        mfs = list(MANIFEST_DIR.glob("*.json"))
        if not mfs:
            return 0
        all_h = []
        for mf in mfs:
            try:
                with open(mf, "r", encoding="utf-8") as f:
                    data = json.load(f)
                for h in data.get("handlers", []):
                    tn = h.get("tool_name", "")
                    hf = h.get("handler_func", "")
                    if tn and hf:
                        all_h.append((tn, hf))
                mf.unlink()
            except:
                mf.unlink()
        if not all_h:
            return 0
        try:
            with open(REGISTRY_FILE, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
        except:
            return 0
        existing = set(re.findall(r'r\.handlers\["([^"]+)"\]', content))
        to_add = []
        added = 0
        for tn, hf in all_h:
            if tn not in existing and hf not in content:
                to_add.append(f'\tr.handlers["{tn}"] = {hf}')
                added += 1
                existing.add(tn)
        if not added:
            return 0
        insert = "\n".join(to_add) + "\n"
        lines = content.split("\n")
        idx = -1
        depth = 0
        in_func = False
        for i, line in enumerate(lines):
            if "func (r *Registry) registerAll()" in line:
                in_func = True
                depth = 0
            if in_func:
                depth += line.count("{") - line.count("}")
                if depth <= 0 and i > 0:
                    idx = i
                    in_func = False
                    break
        if idx < 0:
            for i in range(len(lines) - 1, -1, -1):
                if lines[i].strip() == "}":
                    idx = i
                    break
        if idx >= 0:
            lines.insert(idx, insert)
            with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            log.ok(f"Merged {added} handlers")
        return added


# === WORKER — 3-Phase Pipeline ===
def worker_loop(worker_id, shutdown, completed_lock, completed_count):
    stagger = (worker_id - 1) * 5  # 5s between workers (50 workers = ~4min stagger)
    if stagger > 0:
        log.info(f"Staggering {stagger}s", worker_id)
        for _ in range(stagger):
            if shutdown.is_set():
                return
            time.sleep(1)

    while not shutdown.is_set():
        task = claim_task(worker_id)
        if not task:
            log.info("No more tasks", worker_id)
            return
        name = task["name"]
        fn = name_to_filename(name)
        log.info(f"Claimed: {name} -> {fn}.go", worker_id)

        # === PHASE 1: GENERATE ===
        log.phase(f"GEN: {name}", worker_id)

        # Fetch original source code if GitHub URL is available
        sources = {}
        github_url = task.get("github_url", "")
        if github_url and "github.com" in github_url:
            log.info(f"Fetching source for {name}: {github_url}", worker_id)
            temp_dir = tempfile.mkdtemp(prefix="mcp_src_")
            try:
                sources = fetch_source_code(github_url, temp_dir)
                if sources:
                    log.info(f"Got {len(sources)} source files for {name}", worker_id)
                else:
                    log.warn(f"No source files fetched for {name}", worker_id)
            except Exception as e:
                log.warn(f"Source fetch failed for {name}: {e}", worker_id)
            finally:
                # Clean up temp dir
                try:
                    import shutil

                    shutil.rmtree(temp_dir, ignore_errors=True)
                except Exception:
                    pass

        prompt, system = make_gen_prompt(task, sources=sources if sources else None)
        output = llm.call(prompt, system, phase="gen", wid=worker_id)
        if not output:
            fail_task(name, "gen: LLM failed")
            log.err(f"GEN FAIL: {name}", worker_id)
            log.record_phase("gen", False)
            continue
        go_code, manifest = extract_go_code(output, fn)
        if not go_code or "package tools" not in go_code:
            fail_task(name, "gen: no code")
            log.err(f"GEN NO-CODE: {name}", worker_id)
            log.record_phase("gen", False)
            continue
        if "package main" in go_code:
            fail_task(name, "gen: package main")
            log.record_phase("gen", False)
            continue
        if go_code.count("func (ctx context.Context)") > 3:
            fail_task(name, "gen: garbage")
            log.record_phase("gen", False)
            continue
        if "type ToolResponse struct" in go_code:
            go_code = re.sub(
                r"type ToolResponse struct\s*\{.*?\}", "", go_code, flags=re.DOTALL
            )
            go_code = re.sub(
                r"type TextContent struct\s*\{.*?\}", "", go_code, flags=re.DOTALL
            )
        external = re.findall(r'"(github\.com/(?!tormentnexushq)[^"]+)"', go_code)
        if external:
            go_code = re.sub(
                r'\s*"[^"]*github\.com/(?!tormentnexushq)[^"]*"\s*\n?', "\n", go_code
            )
            log.warn(f"GEN: stripped {len(external)} external imports", worker_id)
        handlers_found = re.findall(r"func (Handle\w+)\s*\(", go_code)
        if not handlers_found:
            fail_task(name, "gen: no handlers")
            log.err(f"GEN NO-HANDLER: {name}", worker_id)
            log.record_phase("gen", False)
            continue
        log.ok(f"GEN OK: {name} ({len(handlers_found)} handlers)", worker_id)
        log.record_phase("gen", True)
        time.sleep(PIPELINE_COOLDOWN)

        # === PHASE 2: REVIEW (2 independent reviewers) ===
        log.phase(f"REV: {name} (x2)", worker_id)
        rev_prompt, rev_system = make_review_prompt(go_code)
        reviews = []
        for rev_num in range(2):
            review_output = llm.call(
                rev_prompt, rev_system, phase="rev", wid=worker_id, max_retries=3
            )
            if review_output:
                compiles, errors = parse_review(review_output)
                reviews.append({"compiles": compiles, "errors": errors})
                log.info(
                    f"REV-{rev_num + 1}: compiles={compiles} err={errors[:3]}",
                    worker_id,
                )
                log.record_phase("rev", True)
            else:
                reviews.append({"compiles": False, "errors": ["review LLM failed"]})
                log.record_phase("rev", False)
            if rev_num == 0:
                time.sleep(PIPELINE_COOLDOWN)

        both_compile = all(r["compiles"] for r in reviews)
        any_compile = any(r["compiles"] for r in reviews)
        all_errors = list(
            dict.fromkeys(e for r in reviews for e in r.get("errors", []))
        )
        if both_compile:
            log.ok(f"REV PASS: {name}", worker_id)
            with log.lock:
                log.phase_stats["rev_agreed"] += 1
        elif any_compile:
            log.warn(f"REV SPLIT: {name} errors={all_errors[:3]}", worker_id)
        else:
            log.warn(f"REV FAIL: {name} errors={all_errors[:3]}", worker_id)

        # === PHASE 3: FIX (if any reviewer found errors) ===
        final_code = go_code
        review_status = "pass"
        if not both_compile and all_errors:
            log.phase(f"FIX: {name} ({len(all_errors)} errors)", worker_id)
            with log.lock:
                log.phase_stats["fix_needed"] += 1
            time.sleep(PIPELINE_COOLDOWN)
            fix_prompt, fix_system = make_fix_prompt(go_code, all_errors)
            fix_output = llm.call(fix_prompt, fix_system, phase="fix", wid=worker_id)
            if fix_output:
                fixed_code, _ = extract_go_code(fix_output, fn)
                if (
                    fixed_code
                    and "package tools" in fixed_code
                    and _has_handlers(fixed_code)
                ):
                    ext2 = re.findall(
                        r'"(github\.com/(?!tormentnexushq)[^"]+)"', fixed_code
                    )
                    if ext2:
                        fixed_code = re.sub(
                            r'\s*"[^"]*github\.com/(?!tormentnexushq)[^"]*"\s*\n?',
                            "\n",
                            fixed_code,
                        )
                    if "type ToolResponse struct" in fixed_code:
                        fixed_code = re.sub(
                            r"type ToolResponse struct\s*\{.*?\}",
                            "",
                            fixed_code,
                            flags=re.DOTALL,
                        )
                        fixed_code = re.sub(
                            r"type TextContent struct\s*\{.*?\}",
                            "",
                            fixed_code,
                            flags=re.DOTALL,
                        )
                    fixed_handlers = re.findall(r"func Handle\w+\s*\(", fixed_code)
                    if fixed_handlers:
                        # Verify the fixed code has balanced braces and no truncation
                        ob = fixed_code.count("{")
                        cb = fixed_code.count("}")
                        if ob != cb:
                            log.warn(
                                f"FIX TRUNCATED: {name} (braces {ob}/{cb}), keeping original",
                                worker_id,
                            )
                            review_status = "fix-truncated-keeporig"
                            log.record_phase("fix", False)
                        else:
                            final_code = fixed_code
                            handlers_found = fixed_handlers
                            review_status = "fixed"
                            log.ok(f"FIX OK: {name}", worker_id)
                            log.record_phase("fix", True)
                    else:
                        review_status = "fix-nohandler-keeporig"
                        log.record_phase("fix", False)
                else:
                    review_status = "fix-nocode-keeporig"
                    log.record_phase("fix", False)
            else:
                review_status = "fix-llmfail-keeporig"
                log.record_phase("fix", False)
        else:
            log.record_phase("fix", True)

        # === SANITIZE CODE ===
        final_code = sanitize_go_code(final_code)

        # === WRITE FILE (with Go compilation check) ===
        go_file = f"{fn}.go"
        # Write to a staging location first
        staging_dir = TOOLS_DIR / "_staging"
        staging_dir.mkdir(exist_ok=True)
        staging_path = staging_dir / go_file
        try:
            with open(staging_path, "w", encoding="utf-8") as f:
                f.write(final_code)
        except Exception as e:
            fail_task(name, f"write error: {e}")
            log.err(f"Write {go_file}: {e}", worker_id)
            continue

        # === ITERATIVE COMPILE CHECK (up to 3 fix-attempts with real Go compiler errors) ===
        # This prevents corrupted .go files from landing in the real tools/ dir.
        compile_ok = False
        compile_errors = ""
        for compile_attempt in range(3):
            # Write the current code to staging
            with open(staging_path, "w", encoding="utf-8") as f:
                f.write(final_code)
            # Copy registry + server so the package can compile
            try:
                for dep in ("registry.go", "server.go"):
                    dep_src = TOOLS_DIR / dep
                    if dep_src.exists():
                        (staging_dir / dep).write_text(
                            dep_src.read_text(encoding="utf-8"), encoding="utf-8"
                        )
                result = subprocess.run(
                    ["go", "build", "./internal/tools/_staging"],
                    capture_output=True,
                    text=True,
                    timeout=30,
                    cwd=str(GO_DIR),
                )
                if result.returncode == 0:
                    compile_ok = True
                    break
                # Extract real compiler errors
                compile_errors = result.stderr[:1000]
                log.warn(
                    f"Compile fail (attempt {compile_attempt + 1}): {compile_errors[:200]}",
                    worker_id,
                )
            except subprocess.TimeoutExpired:
                log.warn(
                    f"Compile timed out (attempt {compile_attempt + 1}), accepting",
                    worker_id,
                )
                compile_ok = True
                break
            except FileNotFoundError:
                log.warn("go not found on PATH, skipping compile check", worker_id)
                compile_ok = True
                break

            if compile_attempt < 2:
                # Feed REAL compiler errors back to LLM for fixing
                log.phase(
                    f"FIX-COMPILE: {name} (attempt {compile_attempt + 1})", worker_id
                )
                fix_prompt, fix_system = make_compile_fix_prompt(
                    final_code, compile_errors
                )
                fix_output = llm.call(
                    fix_prompt,
                    fix_system,
                    phase="fix-compile",
                    wid=worker_id,
                    max_retries=2,
                )
                if fix_output:
                    fixed_code, _ = extract_go_code(fix_output, fn)
                    if (
                        fixed_code
                        and "package tools" in fixed_code
                        and _has_handlers(fixed_code)
                    ):
                        # Clean external imports
                        ext = re.findall(
                            r'"(github\.com/(?!tormentnexushq)[^"]+)"', fixed_code
                        )
                        if ext:
                            fixed_code = re.sub(
                                r'\s*"[^"]*github\.com/(?!tormentnexushq)[^"]*"\s*\n?',
                                "\n",
                                fixed_code,
                            )
                        if "type ToolResponse struct" in fixed_code:
                            fixed_code = re.sub(
                                r"type ToolResponse struct\s*\{.*?\}",
                                "",
                                fixed_code,
                                flags=re.DOTALL,
                            )
                            fixed_code = re.sub(
                                r"type TextContent struct\s*\{.*?\}",
                                "",
                                fixed_code,
                                flags=re.DOTALL,
                            )
                        ob = fixed_code.count("{")
                        cb = fixed_code.count("}")
                        if ob == cb:
                            final_code = fixed_code
                            log.ok(
                                f"Compile fix attempt {compile_attempt + 1}: updated code",
                                worker_id,
                            )
                        else:
                            log.warn(
                                f"Compile fix truncated (braces {ob}/{cb}), keeping previous",
                                worker_id,
                            )
                    else:
                        log.warn(
                            "Compile fix produced invalid code, keeping previous",
                            worker_id,
                        )
                else:
                    log.warn("Compile fix LLM failed, keeping previous", worker_id)
                time.sleep(1)

        if not compile_ok:
            log.warn(
                f"Compile FAILED after 3 attempts for {go_file}: {compile_errors[:200]}",
                worker_id,
            )
            # Write to broken directory
            broken_fix_dir = TOOLS_DIR / "_broken"
            broken_fix_dir.mkdir(exist_ok=True)
            (broken_fix_dir / go_file).write_text(final_code, encoding="utf-8")
            staging_path.unlink(missing_ok=True)
            fail_task(name, f"compile failed after 3 tries: {compile_errors[:200]}")
            continue

        # Compilation passed — promote from staging to real tools/
        if staging_path.exists():
            shutil.copy2(staging_path, TOOLS_DIR / go_file)
            staging_path.unlink(missing_ok=True)
            log.ok(f"Compile check PASSED for {go_file}", worker_id)
    if manifest:
        MANIFEST_DIR.mkdir(exist_ok=True)
        try:
            with open(MANIFEST_DIR / f"{fn}.json", "w", encoding="utf-8") as f:
                json.dump(manifest, f, indent=2)
        except:
            pass
        tc = len(handlers_found)
        complete_task(name, go_file, tc, review_status)
        log.ok(f"DONE: {name} ({tc}h, {review_status})", worker_id)
    with completed_lock:
        completed_count[0] += 1


# === WORKER — Validation Phase ===
def worker_validate(worker_id, shutdown, completed_lock, completed_count):
    stagger = (worker_id - 1) * 3
    if stagger:
        time.sleep(stagger)

    while not shutdown.is_set():
        task = claim_implemented_task(worker_id)
        if not task:
            log.info("No more servers to validate", worker_id)
            return
        name = task["name"]
        github_url = task["github_url"]

        # Find the Go file
        fn = name_to_filename(name) + ".go"
        go_path = TOOLS_DIR / fn
        if not go_path.exists():
            # Try fuzzy match
            matches = list(TOOLS_DIR.glob("*.go"))
            go_code = ""
            for m in matches:
                if name.lower()[:15] in m.stem.lower():
                    go_code = m.read_text(encoding="utf-8", errors="replace")
                    fn = m.name
                    break
            if not go_code:
                record_validation(name, "MISSING", f"no Go file for {name}")
                with completed_lock:
                    completed_count[0] += 1
                continue
        else:
            go_code = go_path.read_text(encoding="utf-8", errors="replace")

        if not go_code.strip() or "//go:build ignore" in go_code:
            record_validation(name, "STUB", "build-constrained stub, no implementation")
            with completed_lock:
                completed_count[0] += 1
            continue

        # Fetch original MCP server info from GitHub
        original_info = ""
        if github_url and "github.com" in github_url:
            raw_base = github_url.rstrip("/").replace(
                "github.com", "raw.githubusercontent.com"
            )
            for branch in ["main", "master"]:
                for path in ["README.md", "package.json", "mcp.json"]:
                    try:
                        req = urllib.request.Request(
                            f"{raw_base}/{branch}/{path}",
                            headers={"User-Agent": "Mozilla/5.0"},
                        )
                        with urllib.request.urlopen(req, timeout=10) as r:
                            original_info += f"\n[{branch}/{path}]:\n{r.read().decode('utf-8', errors='replace')[:5000]}"
                    except Exception:
                        continue
                if original_info:
                    break

        if not original_info:
            record_validation(
                name, "NO_ORIGINAL", f"cannot fetch source from {github_url}"
            )
            with completed_lock:
                completed_count[0] += 1
            continue

        # Use LLM to validate
        log.phase(f"VALIDATE: {name}", worker_id)
        prompt = f"""You are validating a Go port of an MCP server.

Original MCP server ({name}):
Source: {github_url}
{original_info[:4000]}

Go port:
```go
{go_code[:4000]}
```

Is this a CLEAN_PORT, PARTIAL_PORT, MISMATCH, or STUB_ONLY?
Reply with exactly one keyword on the first line, then a brief explanation on the second line."""

        result = llm.call(prompt, "", phase="validate", wid=worker_id)
        if not result:
            record_validation(name, "LLM_FAIL", "LLM call failed")
            with completed_lock:
                completed_count[0] += 1
            continue

        lines = result.strip().split("\n")
        status = lines[0].strip().upper() if lines else "UNKNOWN"
        detail = lines[1].strip()[:100] if len(lines) > 1 else ""

        for valid in ["CLEAN_PORT", "PARTIAL_PORT", "MISMATCH", "STUB_ONLY"]:
            if valid in status:
                status = valid
                break
        else:
            status = "UNKNOWN"
            detail = result[:100]

        record_validation(name, status, detail)
        if status == "CLEAN_PORT":
            log.ok(f"VALIDATE OK: {name} -> {status}", worker_id)
        else:
            log.warn(f"VALIDATE: {name} -> {status} ({detail[:60]})", worker_id)

        with completed_lock:
            completed_count[0] += 1

    with completed_lock:
        completed_count[0] += 1


# === ORCHESTRATOR ===
class Swarm:
    def __init__(
        self, max_workers, limit, forever, repair_only, no_research, validate=False
    ):
        self.max_workers = max_workers
        self.limit = limit
        self.forever = forever
        self.repair_only = repair_only
        self.no_research = no_research
        self.validate = validate
        self.running = True
        self.shutdown = threading.Event()
        self.completed_lock = threading.Lock()
        self.completed_count = [0]
        signal.signal(signal.SIGINT, lambda s, f: self._stop())
        signal.signal(signal.SIGTERM, lambda s, f: self._stop())

    def _stop(self):
        log.stat("Shutdown signal...")
        self.running = False
        self.shutdown.set()

    def run(self):
        log.stat("=" * 70)
        log.stat(" TORMENTNEXUS SWARM v7 - THE VERIFIED ASSIMILATOR")
        log.stat("=" * 70)
        log.stat(
            f"Workers: {self.max_workers} | Limit: {self.limit} | Forever: {self.forever}"
        )
        if self.validate:
            log.stat("Pipeline: VALIDATE (compare Go ports vs original MCP servers)")
        else:
            log.stat("Pipeline: GENERATE -> REVIEW(2) -> FIX")
        log.stat(f"Generator models: {GENERATOR_MODELS[:3]}...")
        log.stat(f"Reviewer models: {REVIEWER_MODELS[:3]}...")
        log.stat(f"Fixer models: {FIXER_MODELS[:3]}...")
        t, i, p, f = get_stats()
        log.stat(f"DB: {t} total | {i} done | {p} pending | {f} failed")
        MANIFEST_DIR.mkdir(exist_ok=True)
        stale = reset_stale()
        if stale:
            log.info(f"Released {stale} stale tasks")
        if not proxy.check():
            log.warn("Proxy not healthy - restarting...")
            if not proxy.restart():
                log.err("Cannot start proxy!")
                return False
        if self.repair_only:
            repair_build()
            merge_manifests()
            verify_build()
            return True
        log.stat("Checking build...")
        repair_build()
        merge_manifests()
        verify_build()
        while self.running:
            try:
                self._run_wave()
            except Exception as e:
                log.err(f"Wave error: {e}")
                traceback.print_exc()
                if not self.forever:
                    break
                time.sleep(30)
            if not self.forever and self.completed_count[0] >= self.limit:
                log.stat(f"Limit reached ({self.limit})!")
                break
            _, _, pending, failed = get_stats()
            if pending == 0:
                if self.forever and failed > 0:
                    n = reset_failed(limit=50)
                    if n > 0:
                        log.stat(f"Retrying {n} failed tasks")
                        continue
                log.stat("No pending tasks!")
                if self.forever:
                    log.info("Waiting 60s for next cycle...")
                    time.sleep(60)
                    continue
                break
            if self.forever:
                n = reset_failed(limit=20)
                if n:
                    log.info(f"Auto-retry: {n} failed tasks")
                    time.sleep(5)
        self._shutdown()
        return True

    def _run_wave(self):
        ws = self.max_workers
        if not self.forever:
            ws = min(ws, max(self.limit - self.completed_count[0], 1))
        log.stat(f"Wave: {ws} workers")
        before = self.completed_count[0]
        with ThreadPoolExecutor(max_workers=ws) as pool:
            futs = {}
            for wid in range(1, ws + 1):
                if self.shutdown.is_set():
                    break
                futs[
                    pool.submit(
                        (worker_validate if self.validate else worker_loop),
                        wid,
                        self.shutdown,
                        self.completed_lock,
                        self.completed_count,
                    )
                ] = wid
            last_bc = 0
            for f in as_completed(futs):
                if self.shutdown.is_set():
                    break
                try:
                    f.result()
                except Exception as e:
                    log.err(f"Worker {futs[f]}: {e}")
                now = self.completed_count[0]
                if now - last_bc >= BUILD_VERIFY_EVERY:
                    merge_manifests()
                    repair_build()
                    last_bc = now
        merge_manifests()
        repair_build()
        delta = self.completed_count[0] - before
        t, i, p, f2 = get_stats()
        log.stat(
            f"Wave done: +{delta} | DB: {i}/{t} done, {p} pend, {f2} fail | {log.summary()}"
        )

    def _shutdown(self):
        log.stat("Shutting down...")
        merge_manifests()
        repair_build()
        n = _remove_external_imports()
        if n:
            log.info(f"Removed {n} files with external imports")
        repair_build()
        tc = len(list(TOOLS_DIR.glob("*.go")))
        try:
            hc = len(
                re.findall(
                    r"r\.handlers\[",
                    REGISTRY_FILE.read_text(encoding="utf-8", errors="replace"),
                )
            )
        except:
            hc = 0
        t, i, p, f = get_stats()
        log.stat("=" * 70)
        log.stat(" FINAL STATE")
        log.stat("=" * 70)
        log.stat(f" Tool files: {tc} | Handlers: {hc}")
        log.stat(f" DB: {i}/{t} done, {p} pending, {f} failed")
        log.stat(f" Pipeline: {log.phase_stats}")
        log.stat(f" {log.summary()}")
        log.stat("=" * 70)


# === MAIN ===
def main():
    ap = argparse.ArgumentParser(
        description="TormentNexus Swarm v7 - The Verified Assimilator"
    )
    ap.add_argument("--workers", type=int, default=5)
    ap.add_argument("--limit", type=int, default=50)
    ap.add_argument("--forever", action="store_true")
    ap.add_argument("--repair", action="store_true")
    ap.add_argument(
        "--validate",
        action="store_true",
        help="Validate Go ports against original MCP servers",
    )
    ap.add_argument("--no-research", action="store_true", default=True)
    ap.add_argument("--proxy", type=str, default=None)
    ap.add_argument("--log", type=str, default=None)
    args = ap.parse_args()
    if args.proxy:
        global PROXY_URL
        PROXY_URL = args.proxy
    log.path = args.log or str(
        WORKSPACE / "data" / f"swarm_v7_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    )
    (WORKSPACE / "data").mkdir(exist_ok=True)
    swarm = Swarm(
        max_workers=args.workers,
        limit=args.limit,
        forever=args.forever,
        repair_only=args.repair,
        no_research=args.no_research,
        validate=args.validate,
    )
    success = swarm.run()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
